-- Common/seasonal commodities only. NO prices, shops or fictional listings.
-- Existing administrator edits are preserved when rerun.
begin;
insert into public.mandi_items(id,name,hindi_name,category,default_unit) values
 ('potato','Potato','आलू','Vegetables','kg'),
 ('onion','Onion','प्याज','Vegetables','kg'),
 ('tomato','Tomato','टमाटर','Vegetables','kg'),
 ('brinjal','Brinjal','बैंगन','Vegetables','kg'),
 ('round-brinjal','Round brinjal','गोल बैंगन','Vegetables','kg'),
 ('green-peas','Green peas','हरा मटर','Vegetables','kg'),
 ('cauliflower','Cauliflower','फूलगोभी','Vegetables','kg'),
 ('cabbage','Cabbage','पत्तागोभी','Vegetables','kg'),
 ('okra','Okra / bhindi','भिंडी','Vegetables','kg'),
 ('bottle-gourd','Bottle gourd','लौकी','Vegetables','kg'),
 ('bitter-gourd','Bitter gourd','करेला','Vegetables','kg'),
 ('ridge-gourd','Ridge gourd','तोरई','Vegetables','kg'),
 ('sponge-gourd','Sponge gourd','नेनुआ','Vegetables','kg'),
 ('pointed-gourd','Pointed gourd','परवल','Vegetables','kg'),
 ('ivy-gourd','Ivy gourd','कुंदरू','Vegetables','kg'),
 ('snake-gourd','Snake gourd','चिचिंडा','Vegetables','kg'),
 ('ash-gourd','Ash gourd','पेठा','Vegetables','kg'),
 ('pumpkin','Pumpkin','कद्दू','Vegetables','kg'),
 ('apple-gourd','Apple gourd / tinda','टिंडा','Vegetables','kg'),
 ('cucumber','Cucumber','खीरा','Vegetables','kg'),
 ('long-cucumber','Long cucumber','ककड़ी','Vegetables','kg'),
 ('carrot','Carrot','गाजर','Vegetables','kg'),
 ('radish','Radish','मूली','Vegetables','kg'),
 ('beetroot','Beetroot','चुकंदर','Vegetables','kg'),
 ('turnip','Turnip','शलजम','Vegetables','kg'),
 ('sweet-potato','Sweet potato','शकरकंद','Vegetables','kg'),
 ('colocasia','Colocasia / arbi','अरबी','Vegetables','kg'),
 ('elephant-yam','Elephant foot yam','ओल / सूरन','Vegetables','kg'),
 ('yam','Yam','रतालू','Vegetables','kg'),
 ('green-banana','Raw banana','कच्चा केला','Vegetables','kg'),
 ('green-papaya','Raw papaya','कच्चा पपीता','Vegetables','kg'),
 ('raw-jackfruit','Raw jackfruit','कच्चा कटहल','Vegetables','kg'),
 ('drumstick','Drumstick','सहजन','Vegetables','kg'),
 ('french-beans','French beans','फ्रेंच बीन्स','Vegetables','kg'),
 ('broad-beans','Broad beans','बाकला','Vegetables','kg'),
 ('cluster-beans','Cluster beans','ग्वार फली','Vegetables','kg'),
 ('cowpea-beans','Cowpea / long beans','बोड़ा / लोबिया फली','Vegetables','kg'),
 ('flat-beans','Flat beans','सेम','Vegetables','kg'),
 ('capsicum','Green capsicum','शिमला मिर्च','Vegetables','kg'),
 ('red-capsicum','Red capsicum','लाल शिमला मिर्च','Vegetables','kg'),
 ('yellow-capsicum','Yellow capsicum','पीली शिमला मिर्च','Vegetables','kg'),
 ('green-chilli','Green chilli','हरी मिर्च','Vegetables','kg'),
 ('ginger','Fresh ginger','अदरक','Vegetables','kg'),
 ('garlic','Garlic','लहसुन','Vegetables','kg'),
 ('spring-onion','Spring onion','हरा प्याज','Vegetables','kg'),
 ('lemon','Lemon','नींबू','Vegetables','kg'),
 ('mushroom','Mushroom','मशरूम','Vegetables','kg'),
 ('baby-corn','Baby corn','बेबी कॉर्न','Vegetables','kg'),
 ('sweet-corn','Sweet corn','मक्का','Vegetables','kg'),
 ('broccoli','Broccoli','ब्रोकली','Vegetables','kg'),
 ('lettuce','Lettuce','लेट्यूस','Vegetables','kg'),
 ('celery','Celery','अजमोद','Vegetables','kg'),
 ('zucchini','Zucchini','ज़ुकीनी','Vegetables','kg'),
 ('spinach','Spinach','पालक','Vegetables','bunch'),
 ('fenugreek-leaves','Fenugreek leaves','मेथी साग','Vegetables','bunch'),
 ('mustard-greens','Mustard greens','सरसों साग','Vegetables','bunch'),
 ('bathua','Bathua greens','बथुआ साग','Vegetables','bunch'),
 ('amaranth-greens','Amaranth greens','चौलाई साग','Vegetables','bunch'),
 ('coriander-leaves','Coriander leaves','हरा धनिया','Vegetables','bunch'),
 ('mint','Mint leaves','पुदीना','Vegetables','bunch'),
 ('curry-leaves','Curry leaves','करी पत्ता','Vegetables','bunch'),
 ('red-amaranth','Red amaranth','लाल साग','Vegetables','bunch'),
 ('water-spinach','Water spinach','कलमी साग','Vegetables','bunch'),
 ('malabar-spinach','Malabar spinach','पोई साग','Vegetables','bunch'),
 ('colocasia-leaves','Colocasia leaves','अरबी पत्ता','Vegetables','bunch'),
 ('lotus-stem','Lotus stem','कमल ककड़ी','Vegetables','kg'),
 ('kohlrabi','Kohlrabi','गांठगोभी','Vegetables','kg'),
 ('bamboo-shoots','Bamboo shoots','बाँस की कोपल','Vegetables','kg'),
 ('banana','Banana','केला','Fruits','dozen'),
 ('apple','Apple','सेब','Fruits','kg'),
 ('orange','Orange','संतरा','Fruits','kg'),
 ('sweet-lime','Sweet lime / mosambi','मौसंबी','Fruits','kg'),
 ('mango','Mango','आम','Fruits','kg'),
 ('langra-mango','Langra mango','लंगड़ा आम','Fruits','kg'),
 ('malda-mango','Malda mango','मालदा आम','Fruits','kg'),
 ('dussehri-mango','Dussehri mango','दशहरी आम','Fruits','kg'),
 ('safeda-mango','Safeda mango','सफेदा आम','Fruits','kg'),
 ('alphonso-mango','Alphonso mango','अल्फांसो आम','Fruits','kg'),
 ('guava','Guava','अमरूद','Fruits','kg'),
 ('papaya','Papaya','पपीता','Fruits','kg'),
 ('pomegranate','Pomegranate','अनार','Fruits','kg'),
 ('green-grapes','Green grapes','हरे अंगूर','Fruits','kg'),
 ('black-grapes','Black grapes','काले अंगूर','Fruits','kg'),
 ('watermelon','Watermelon','तरबूज','Fruits','kg'),
 ('muskmelon','Muskmelon','खरबूजा','Fruits','kg'),
 ('lychee','Lychee','लीची','Fruits','kg'),
 ('pineapple','Pineapple','अनानास','Fruits','piece'),
 ('coconut','Coconut','नारियल','Fruits','piece'),
 ('tender-coconut','Tender coconut','हरा नारियल','Fruits','piece'),
 ('pear','Pear','नाशपाती','Fruits','kg'),
 ('peach','Peach','आड़ू','Fruits','kg'),
 ('plum','Plum','आलूबुखारा','Fruits','kg'),
 ('apricot','Apricot','खुबानी','Fruits','kg'),
 ('cherry','Cherry','चेरी','Fruits','kg'),
 ('strawberry','Strawberry','स्ट्रॉबेरी','Fruits','kg'),
 ('kiwi','Kiwi','कीवी','Fruits','kg'),
 ('chikoo','Sapodilla / chikoo','चीकू','Fruits','kg'),
 ('custard-apple','Custard apple','सीताफल','Fruits','kg'),
 ('jackfruit','Ripe jackfruit','पका कटहल','Fruits','kg'),
 ('jamun','Jamun','जामुन','Fruits','kg'),
 ('ber','Indian jujube / ber','बेर','Fruits','kg'),
 ('amla','Indian gooseberry / amla','आंवला','Fruits','kg'),
 ('bael','Bael','बेल','Fruits','kg'),
 ('wood-apple','Wood apple','कैथा','Fruits','kg'),
 ('dates','Fresh dates','खजूर','Fruits','kg'),
 ('fig','Fresh fig','अंजीर','Fruits','kg'),
 ('dragon-fruit','Dragon fruit','ड्रैगन फ्रूट','Fruits','kg'),
 ('passion-fruit','Passion fruit','कृष्ण फल','Fruits','kg'),
 ('avocado','Avocado','एवोकाडो','Fruits','kg'),
 ('pomelo','Pomelo','चकोतरा','Fruits','kg'),
 ('grapefruit','Grapefruit','ग्रेपफ्रूट','Fruits','kg'),
 ('raspberry','Raspberry','रसभरी','Fruits','kg'),
 ('mulberry','Mulberry','शहतूत','Fruits','kg'),
 ('star-fruit','Star fruit','कमरख','Fruits','kg'),
 ('persimmon','Persimmon','तेंदू फल','Fruits','kg'),
 ('rambutan','Rambutan','रामबुतान','Fruits','kg'),
 ('longan','Longan','लोंगन','Fruits','kg')
on conflict(id) do nothing;
commit;
