import '../../lib/core/domain/market.dart';

MarketSnapshot exampleMarket() {
  final time = DateTime.utc(2026, 10, 1);
  final shops = [
    Shop(
      id: 'sample-grocery',
      reviewStatus: 'approved',
      ownerId: 'sample-owner-1',
      name: 'Sample Daily Needs',
      category: 'Grocery',
      area: 'Danapur Bazaar',
      address: 'Example address • Danapur Bazaar',
      phone: '',
      updatedAt: time,
      description:
          'An example neighbourhood grocery shop. Not a real business listing.',
      hours: 'Example: 8 AM – 9 PM',
    ),
    Shop(
      id: 'sample-electronics',
      reviewStatus: 'approved',
      ownerId: 'sample-owner-2',
      name: 'Sample Gadget Corner',
      category: 'Electronics',
      area: 'Saguna More',
      address: 'Example address • Saguna More',
      phone: '',
      updatedAt: time,
      description:
          'Example gadgets and accessories. Not a real business listing.',
    ),
    Shop(
      id: 'sample-fashion',
      reviewStatus: 'approved',
      ownerId: 'sample-owner-3',
      name: 'Sample Style Studio',
      category: 'Fashion',
      area: 'Gola Road',
      address: 'Example address • Gola Road',
      phone: '',
      updatedAt: time,
      description: 'Example clothing listings. Not a real business listing.',
    ),
    Shop(
      id: 'sample-home',
      reviewStatus: 'approved',
      ownerId: 'sample-owner-4',
      name: 'Sample Home & Kitchen',
      category: 'Home',
      area: 'RPS More',
      address: 'Example address • RPS More',
      phone: '',
      updatedAt: time,
      description: 'Example home essentials. Not a real business listing.',
    ),
    Shop(
      id: 'sample-food',
      reviewStatus: 'approved',
      ownerId: 'sample-owner-5',
      name: 'Sample Sweet Shop',
      category: 'Food & sweets',
      area: 'Danapur Bazaar',
      address: 'Example address • Danapur Bazaar',
      phone: '',
      updatedAt: time,
      description: 'Example sweet shop. Not a real business listing.',
    ),
  ];
  final products = [
    Product(
      id: 'sample-rice',
      shopId: shops[0].id,
      name: 'Everyday premium rice',
      category: 'Grocery',
      pricePaise: 7200,
      mrpPaise: 8500,
      unit: '1 kg',
      illustration: 'rice',
      updatedAt: time.add(const Duration(minutes: 9)),
    ),
    Product(
      id: 'sample-earbuds',
      shopId: shops[1].id,
      name: 'Wireless earbuds',
      category: 'Electronics',
      pricePaise: 99900,
      mrpPaise: 129900,
      unit: 'pair',
      illustration: 'earbuds',
      updatedAt: time.add(const Duration(minutes: 8)),
    ),
    Product(
      id: 'sample-shirt',
      shopId: shops[2].id,
      name: 'Everyday cotton shirt',
      category: 'Fashion',
      pricePaise: 59900,
      mrpPaise: 79900,
      unit: 'piece',
      illustration: 'shirt',
      updatedAt: time.add(const Duration(minutes: 7)),
    ),
    Product(
      id: 'sample-pan',
      shopId: shops[3].id,
      name: 'Non-stick everyday pan',
      category: 'Home',
      pricePaise: 74900,
      mrpPaise: 99900,
      unit: 'piece',
      illustration: 'pan',
      updatedAt: time.add(const Duration(minutes: 6)),
    ),
    Product(
      id: 'sample-oil',
      shopId: shops[0].id,
      name: 'Cold-pressed mustard oil',
      category: 'Grocery',
      pricePaise: 18000,
      mrpPaise: 21000,
      unit: '1 litre',
      illustration: 'oil',
      updatedAt: time.add(const Duration(minutes: 5)),
    ),
    Product(
      id: 'sample-watch',
      shopId: shops[1].id,
      name: 'Everyday smart watch',
      category: 'Electronics',
      pricePaise: 149900,
      mrpPaise: 199900,
      unit: 'piece',
      illustration: 'watch',
      updatedAt: time.add(const Duration(minutes: 4)),
    ),
    Product(
      id: 'sample-sweets',
      shopId: shops[4].id,
      name: 'Assorted sweets box',
      category: 'Food & sweets',
      pricePaise: 32000,
      unit: '500 g box',
      illustration: 'sweets',
      updatedAt: time.add(const Duration(minutes: 3)),
    ),
    Product(
      id: 'sample-milk',
      shopId: shops[0].id,
      name: 'Fresh full-cream milk',
      category: 'Grocery',
      pricePaise: 6400,
      unit: '1 litre',
      illustration: 'milk',
      isAvailable: false,
      updatedAt: time.add(const Duration(minutes: 2)),
    ),
  ];
  return MarketSnapshot(shops: shops, products: products);
}
